### Register
POST http://localhost:7070/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "parentName": "Luke"
}

### Login
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "1234"
}