### Get checkins
GET http://localhost:7075/api/playgrounds/1/checkins
Authorization: Bearer {{token}}



### Create checkin
POST http://localhost:7075/api/playgrounds/1/checkins/checkin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "playground_id": 1,
  "user_id": 1,
  "children": [
    {
      "id": 4
    }
  ],
  "check_in": "2026-05-25T14:00:00"
}
###
PUT http://localhost:7075/api/playgrounds/1/checkins/checkout
Authorization: Bearer {{token}}

###
POST http://localhost:7075/api/checkoutall
Authorization: Bearer {{token}}
###
GET http://localhost:7075/api/checkin/1
Authorization: Bearer {{token}}

