### Create a facility
POST http://localhost:7075/api/facility/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Toilet"
}
### Create a facility
POST http://localhost:7075/api/facility/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Gynger"
}
### Create a facility
POST http://localhost:7075/api/facility/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Rutsjebane"
}


### add facility to playground
POST http://localhost:7075/api/playgrounds/1/facility/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "facility_id": 3,
  "playground_id": 2
}
###
GET http://localhost:7075/api/facility
Content-Type: application/json

###

### Create and attach facility
POST http://localhost:7075/api/playgrounds/1/facility/createandattach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "playground_id": 1,
  "facility_name": "Førstehjælpsstation"
}

