### Get all playgrounds
GET http://localhost:7075/api/playgrounds
Authorization: Bearer {{token}}

###
GET http://localhost:7075/api/playgrounds/1
Authorization: Bearer {{token}}

### import playgrounds

POST {{base}}/playgrounds/import
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "lat": 55.68,
  "lng": 12.57,
  "radius": 1000
}

### Get playgrounds near me
POST http://localhost:7075/api/playgrounds/nearme
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "latitude": 55.68,
  "longitude": 12.57,
  "radiusInMeters": 1000,
  "size": 10,
  "page": 1

}

### Create playground
POST {{base}}/playgrounds/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New Playground",
  "lat": 55.68,
  "lng": 12.57
}

