### Get all playgrounds
GET http://localhost:7075/api/playgrounds
Authorization: Bearer {{token}}

### Get facility
GET http://localhost:7075/api/playgrounds/1/facility
Authorization: Bearer {{token}}

### Update facility
PUT http://localhost:7075/api/playgrounds/1/facility
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "toilet": true,
  "swings": true,
  "slide": true
}

### import playgrounds

POST {{base}}/playgrounds/import
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "lat": 55.68,
  "lng": 12.57,
  "radius": 1000
}